spring:
  application:
    name: gateway

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  ignored-services: "*"
  routes:
    item-service:
      path: /item/**
      serviceId: item
    cart-service:
      path: /cart/**
      serviceId: cart

integration-routing-configuration:
  map:
    apple: /item/0
    banana: /item/1
    orange: /item/2
    bread: /item/3
    eggs: /item/4
    milk: /item/5
    juice: /item/6

logging:
  level:
    org.springframework.cloud.netflix.zuul: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
