spring:
  application:
    name: gateway

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  ignored-services: "*"
  routes:
    item-service:
      path: /item/**
      serviceId: item
    cart-service:
      path: /cart/**
      serviceId: cart
    integration: /integration/**
  host:
    socket-timeout-millis: 10000  

ribbon:
  ReadTimeout: 10000

integration-routing-configuration:
  serviceId: integration
  forwardTo: item
  map:
    apple: '0'
    banana: '1'
    orange: '2'
    bread: '3'
    eggs: '4'
    milk: '5'
    juice: '6'

logging:
  level:
    org.springframework.cloud.netflix.zuul: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
