spring:
  application:
    name: springsecurity
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/openam/oauth2
    
server:
  port: 8081

logging:
  level:
    org.springframework.security: DEBUG

openam:
  amadmin:
    username: amadmin
    password: dsiscool02